// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function formatDirectory(inputDir, outputDir) {
  var format = (require("cdb-formatter"));
  return Curry._2(format, inputDir, outputDir);
}

function formatCards(param) {
  return formatDirectory("./temp", "./temp-formatted");
}

exports.formatDirectory = formatDirectory;
exports.formatCards = formatCards;
/* No side effect */
