// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function convertDirectory(inputDir, outputDir) {
  var cdbToJson = (require("cdb-to-json"));
  return cdbToJson(inputDir, outputDir);
}

function parseCards(dirs) {
  return Belt_Array.forEach(dirs, (function (dirname) {
                return convertDirectory(dirname, "./temp");
              }));
}

exports.convertDirectory = convertDirectory;
exports.parseCards = parseCards;
/* No side effect */
