// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Parser = require("./Parser.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var CdbFormatter = require("cdb-formatter");

function formatFile(file, outputDir) {
  CdbFormatter.formatData(file, outputDir);
  
}

function formatCards(param) {
  var filenames = Fs.readdirSync("./temp");
  var files = Belt_Array.map(filenames, (function (filename) {
          var pathname = "./temp/" + filename;
          return Parser.check(Fs.readFileSync(pathname));
        }));
  Belt_Array.forEachWithIndex(files, (function (index, file) {
          var filename = Caml_array.get(filenames, index);
          CdbFormatter.formatData([file], "./cards-json/" + filename + ".json");
          
        }));
  var formattedFiles = Belt_Array.map(filenames, (function (filename) {
          return Fs.readFileSync("./cards-json/" + filename + ".json");
        }));
  return Belt_Array.forEachWithIndex(formattedFiles, (function (index, file) {
                var filename = Caml_array.get(filenames, index);
                var parsedFilename = filename.split(".json");
                var output = "module.exports = " + file;
                Fs.writeFileSync("./cards/" + Caml_array.get(parsedFilename, 0) + ".js", output);
                
              }));
}

exports.formatFile = formatFile;
exports.formatCards = formatCards;
/* fs Not a pure module */
