// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Parser = require("./Parser.bs.js");

function jsonToConfig(json) {
  return Parser.parse(Parser.check(json));
}

function readConfig(param) {
  return Fs.readFileSync("./config.json");
}

function checkForConfig(param) {
  var files = Fs.readdirSync("./");
  return files.includes("config.json");
}

exports.jsonToConfig = jsonToConfig;
exports.readConfig = readConfig;
exports.checkForConfig = checkForConfig;
/* fs Not a pure module */
