// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$JSON = require("./JSON.bs.js");

function jsonToConfig(json) {
  return $$JSON.parse($$JSON.check(json));
}

function readConfig(param) {
  return "./config.json".readFileSync();
}

function checkForConfig(param) {
  var files = "./".readDirSync();
  return files.includes("config.json");
}

exports.jsonToConfig = jsonToConfig;
exports.readConfig = readConfig;
exports.checkForConfig = checkForConfig;
/* No side effect */
