// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("rescript/lib/js/js_option.js");

function unwrapErr(errObj) {
  return Js_option.getWithDefault({
              message: ""
            }, errObj).message;
}

exports.unwrapErr = unwrapErr;
/* No side effect */
