// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_option = require("rescript/lib/js/js_option.js");

var FS = {};

function unwrapErr(errObj) {
  return Js_option.getWithDefault({
              message: ""
            }, errObj).message;
}

function getConfig(dispatch, param) {
  "./config.json".readFile(function (err, data) {
        var hasError = Js_option.isSome(err);
        if (hasError) {
          return Curry._1(dispatch, /* UserPrompt */1);
        } else {
          return Curry._1(dispatch, {
                      TAG: /* Running */0,
                      _0: JSON.parse(data).paths
                    });
        }
      });
  
}

exports.FS = FS;
exports.unwrapErr = unwrapErr;
exports.getConfig = getConfig;
/* No side effect */
