// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var check = Json.parseOrRaise;

function parse(data) {
  return {
          paths: Json_decode.field("config", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), data)
        };
}

exports.check = check;
exports.parse = parse;
/* No side effect */
