// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Config = require("./Config.bs.js");
var Prompt = require("./Prompt.bs.js");
var CardParser = require("./CardParser.bs.js");
var CardFormatter = require("./CardFormatter.bs.js");

function getDirectoriesFromUser(param) {
  return Prompt.ask("Provide a directory path. Press Ctrl + C to exit. \n").then(function (msg) {
              return Promise.resolve(msg);
            });
}

function fromConfig(param) {
  var configJson = Config.readConfig(undefined);
  var config = Config.jsonToConfig(configJson);
  var paths = config.paths;
  CardParser.parseCards(paths);
  return CardFormatter.formatCards(undefined);
}

function fromInput(param) {
  var action = getDirectoriesFromUser(undefined).then(function (paths) {
        CardParser.parseCards(paths);
        CardFormatter.formatCards(undefined);
        return Promise.resolve(undefined);
      });
  console.log(action);
  
}

function main(param) {
  var hasConfig = Config.checkForConfig(undefined);
  if (hasConfig) {
    return fromConfig(undefined);
  } else {
    return fromInput(undefined);
  }
}

main(undefined);

exports.getDirectoriesFromUser = getDirectoriesFromUser;
exports.fromConfig = fromConfig;
exports.fromInput = fromInput;
exports.main = main;
/*  Not a pure module */
