// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("readline");

function ask(query) {
  var readline = Readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });
  return new Promise((function (resolve, _reject) {
                readline.on("SIGINT", (function () {
                        readline.close();
                        return resolve("");
                      }));
                return readline.question(query, (function (response) {
                              readline.close();
                              return resolve(response);
                            }));
              }));
}

exports.ask = ask;
/* readline Not a pure module */
